dependencies:
- name: activiti-cloud-audit
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.17
- name: activiti-cloud-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.56
- name: application
  repository: file://../application
  version: 0.1.0
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: infrastructure
  repository: file://../infrastructure
  version: 0.1.0
