dependencies:
- name: activiti-cloud-audit
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.15
- name: activiti-cloud-demo-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.41
- name: activiti-cloud-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.54
- name: activiti-cloud-query
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.32
- name: application
  repository: file://../application
  version: 0.1.0
- name: example-runtime-bundle
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.0.49
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: infrastructure
  repository: file://../infrastructure
  version: 0.1.0
